import type { ServiceSpecification } from "@/domain/types";
import { mergePropertiesActionMatrix, mergePropertiesPermissionMatrix } from "@/lib/citizen-service-permission-matrices";
import { mergePropertiesUserStory } from "@/lib/citizen-service-user-stories";

export const citizenServiceSpecifications: Record<string, ServiceSpecification> = {
  "merge-properties": {
    serviceId: "merge-properties",
    serviceCode: "SRV-URB-001",
    legalBasis: "قانون الإدارة المحلية رقم 107 لعام 2011، وقانون التطوير والتنظيم العمراني رقم 23 لعام 2015، وضابطة البناء العامة لبلدية حماة.",
    slaDays: 2,
    slaDescription: "بين 1 إلى 3 أيام عمل رسمية من تاريخ تسجيل الطلب واستيفاء الوثائق المطلوبة والتدقيق الفني.",
    businessGoal: "تمكين مالكي العقارات المتلاصقة من توحيد مقاسمهم ضمن عقار واحد موحد لتنفيذ مشاريع عمرانية أو مطابقة المخطط التنظيمي المعتمد.",
    targetBeneficiary: "أصحاب الحقوق العينية (المالكون أو الوكلاء القانونيون الموثقون) والجهات الهندسية المفوضة.",
    digitalMaturityLevel: "إجراء هجين ورقي/رقمي",
    deliverableType: "تقرير دراسة تنظيمية فنية وموافقة مبدئية على توحيد المقسمين موجهة لأمانة السجل العقاري.",
    officialCertification: "توقيع رئيس شعبة التخطيط والتنظيم، رئيس دائرة التنظيم والتخطيط العمراني، ومصادقة مدير الشؤون الفنية مع الختم الرسمي.",
    fieldsDictionary: [
      {
        name: "اسم مقدم الطلب",
        key: "applicant_name",
        type: "string",
        required: true,
        description: "الاسم الثلاثي أو اسم الشخصية الاعتبارية المتقدمة بطلب الدمج.",
        validationRule: "نص عربي لا يقل عن 6 أحرف ولا يزيد عن 150 حرفاً.",
        example: "محمد أحمد الحمصي",
      },
      {
        name: "رقم الهاتف الجوال",
        key: "mobile_number",
        type: "phone",
        required: true,
        description: "رقم التواصل الخلوي المعتمد لإرسال إشعارات التحديث ومسار المعاملة.",
        validationRule: "صيغة هاتف سوري تبدأ بـ 09 وتتكون من 10 خانات رقمية.",
        example: "0944123456",
      },
      {
        name: "رقم العقار الأول",
        key: "property_number_1",
        type: "number",
        required: true,
        description: "الرقم العقاري الرسمي للمقسم الأول كما هو مقيد بالسجل العقاري.",
        validationRule: "عدد صحيح موجب يتطابق مع قيود السجل العقاري.",
        example: "1420",
      },
      {
        name: "رقم العقار الثاني",
        key: "property_number_2",
        type: "number",
        required: true,
        description: "الرقم العقاري للمقسم الملاصق المراد ضمه للعقار الأول.",
        validationRule: "عدد صحيح موجب مختلف عن رقم العقار الأول ومتصل به جغرافياً.",
        example: "1421",
      },
      {
        name: "اسم المنطقة العقارية",
        key: "cadastral_zone",
        type: "select",
        required: true,
        description: "المنطقة العقارية المعتمدة داخل المخطط التنظيمي العام لمدينة حماة.",
        validationRule: "قيمة معرفة مسبقاً ضمن جدول المناطق العقارية.",
        example: "الحاضر الكبير / المنطقة الأولى",
      },
      {
        name: "صفة مقدم الطلب",
        key: "applicant_capacity",
        type: "select",
        required: true,
        description: "الصفة القانونية لمقدم المعاملة (مالك أصيل، شريك، وكيل قانوني).",
        validationRule: "قيمة من قائمة: [مالك، وكيل قانوني، شريك على الشيوع].",
        example: "مالك",
      },
    ],
    validationConstraints: [
      {
        rule: "شرط التجاور الجغرافي والحد المشترك",
        rationale: "يمنع دمج عقارين يفصل بينهما شارع تنظيمي أو فضلة أملاك عامة غير مشتراة أو عقار لطرف ثالث.",
        severity: "error",
      },
      {
        rule: "تطابق الاستخدام التنظيمي للمقسمين",
        rationale: "يجب أن يقع العقاران ضمن نفس الصفة التنظيمية (سكني/تجاري/صناعي) أو الحصول على تسوية نظامية للاستخدام المختلط.",
        severity: "error",
      },
      {
        rule: "خلو العقارين من موانع الحجز التنفيذي أو إشارات النزع الإجباري",
        rationale: "تدقيق إشارات القيد العقاري لضمان عدم وجود نزاع قضائي مانع للتصرف العقاري.",
        severity: "warning",
      },
    ],
    attachmentsSpecification: [
      {
        name: "بيان قيد عقاري حديث للعقار الأول",
        format: "PDF / JPEG",
        maxSize: "5MB",
        isRequired: true,
        purpose: "إثبات الملكية وتاريخ الصحيفة العقارية وخلوها من الموانع.",
        issuingAuthority: "مديرية المصالح العقارية بحماة (صلاحية 3 أشهر)",
      },
      {
        name: "بيان قيد عقاري حديث للعقار الثاني",
        format: "PDF / JPEG",
        maxSize: "5MB",
        isRequired: true,
        purpose: "مطابقة أسماء المالكين والنسب السهمية والارتفاقات.",
        issuingAuthority: "مديرية المصالح العقارية بحماة (صلاحية 3 أشهر)",
      },
      {
        name: "مخطط كروكي أو تكليف مساحي بالإحداثيات",
        format: "PDF / DWG",
        maxSize: "15MB",
        isRequired: true,
        purpose: "توضيح الحدود المشتركة، واجهة الشارع، والإحداثيات الجغرافية الدقيقة.",
        issuingAuthority: "مهندس طوبوغرافي مرخص أو نقابة المهندسين",
      },
      {
        name: "الوكالة القانونية أو التفويض الرسمي",
        format: "PDF",
        maxSize: "5MB",
        isRequired: false,
        purpose: "إثبات صفة الوكيل في حال عدم تقديم الطلب من المالك مباشرة.",
        issuingAuthority: "الكاتب بالعدل",
      },
    ],
    userStory: mergePropertiesUserStory,
    permissionMatrix: mergePropertiesPermissionMatrix,
    actionPermissionMatrix: mergePropertiesActionMatrix,
    edgeCasesAndReturns: [
      {
        condition: "وجود فارق منسوب شاقولي أو شارع تنظيمي مقترح بين العقارين",
        action: "إحالة المعاملة إلى شعبة التخطيط العمراني للدراسة الميدانية وإصدار تقرير عدم ملاءمة الدمج.",
        returnCode: "ERR_NON_CONTIGUOUS",
      },
      {
        condition: "وجود إشارة رهن بنكي أو حجز احتياطي على أحد العقارين",
        action: "إيقاف إجراءات الدمج ومطالبة صاحب العلاقة بإحضار كتاب عدم ممانعة رسمي من الجهة الدائنة.",
        returnCode: "ERR_LIEN_DETECTED",
      },
      {
        condition: "عدم تطابق الملكيات الفردية بين العقارين في الملكية الشائعة",
        action: "طلب عقد اتفاق توحيد حصص موثق أو توقيع جميع الشركاء على الشيوع.",
        returnCode: "ERR_OWNERSHIP_MISMATCH",
      },
    ],
    apiPayloadExample: JSON.stringify(
      {
        service_id: "merge-properties",
        applicant: {
          name: "محمد أحمد الحمصي",
          phone: "0944123456",
          capacity: "OWNER",
        },
        properties: [
          { number: 1420, zone_id: "Z-01", ownership_ratio: "2400/2400" },
          { number: 1421, zone_id: "Z-01", ownership_ratio: "2400/2400" },
        ],
        documents: [
          { doc_type: "CADASTRAL_EXTRACT_1", file_id: "doc_98124_p1.pdf" },
          { doc_type: "CADASTRAL_EXTRACT_2", file_id: "doc_98125_p2.pdf" },
          { doc_type: "SURVEY_SKETCH", file_id: "survey_1420_1421.dwg" },
        ],
      },
      null,
      2
    ),
    faqs: [
      {
        id: "faq-merge-01",
        category: "إداري وتشغيلي",
        question: "ما هو المسار الإجرائي الزمني الداخلي لمعالجة طلب دمج العقارين؟",
        answer: "يبدأ الطلب في النافذة الواحدة لتسجيل وتوليد الباركود والرقم الموحد، ثم يقيد بديوان الشؤون الفنية، ويحال إلى شعبة أمانة الخارطة لتدقيق التطابق العقاري، ثم شعبة التخطيط لدراسة الواجهات والارتدادات، وينتهي بإعداد كتاب الموافقة وتوقيعه من رئيس الدائرة ومدير الشؤون الفنية خلال 1 إلى 3 أيام عمل.",
      },
      {
        id: "faq-merge-02",
        category: "تقني ونموذج البيانات",
        question: "كيف يتم التحقق آلياً من صحة أرقام العقارات والمناطق العقارية في النظام؟",
        answer: "يتم فحص أرقام العقارات عبر خدمة الربط المباشر مع قاعدة البيانات المكانية (GIS Layer)، والتأكد من مطابقة المنطقة العقارية المختارة مع المضلعات الطبوغرافية، والتأكد البرمجي من أن العقارين يشتركان في خط حدودي (Shared Polygon Edge) بطول أكبر من الصفر.",
      },
      {
        id: "faq-merge-03",
        category: "مالي وقانوني",
        question: "هل تترتب رسوم استملاك أو تحسين تنظيمي عند دمج المقاسم؟",
        answer: "الطلب بحد ذاته لا يتطلب سوى رسم الطابع والمعاملة الفنية المحددة في جدول الرسوم البلدية، ولكن إذا نتج عن الدمج زيادة في عامل الاستثمار السطحي أو الشاقولي للمقسم الجديد، فتحسب فروقات الرسوم لاحقاً عند التقدم بطلب ترخيص البناء.",
      },
      {
        id: "faq-merge-04",
        category: "إجراءات واعتمادات",
        question: "ما هي شروط انتقال المعاملة من مرحلة التدقيق الفني إلى مرحلة المصادقة النهائية؟",
        answer: "يشترط استيفاء ثلاثة شروط: تقرير إيجابي من مهندس المنطقة، سلامة المخطط الطبوغرافي المدقق، ومطابقة القيود مع عدم وجود إشارات حجز قضائية مانعة للتصرف، ويتم حفظ إشعارات الاعتماد في سجل التدقيق (Audit Log).",
      },
    ],
  },

  "purchase-surplus": {
    serviceId: "purchase-surplus",
    serviceCode: "SRV-URB-002",
    legalBasis: "المادة 42 من قانون الإدارة المحلية 107/2011، وقانون بيع وتأجير أملاك الدولة والوحدات الإدارية، ونظام تقدير الفضلات العقارية المعتمد في محافظة حماة.",
    slaDays: 2,
    slaDescription: "بين 1 إلى 3 أيام عمل رسمية من تاريخ تسجيل الطلب واستيفاء الوثائق المطلوبة والتدقيق الفني.",
    businessGoal: "معالجة أوضاع الأجزاء العقارية الزائدة (الفضلات) الملاصقة للأملاك الخاصة وتحقيق الاستفادة التخطيطية والمالية للبلدية وفق الضوابط.",
    targetBeneficiary: "مالك العقار الملاصق للفضلة العقارية حصراً أو من ينوب عنه بوكالة خاصة.",
    digitalMaturityLevel: "إجراء هجين ورقي/رقمي",
    deliverableType: "تقرير لجنة تقدير وتحديد وضع الفضلة وإشعار بإمكانية البيع والتسعير التقديري أو الرفض المعلل.",
    officialCertification: "محضر لجنة الفضلات، توقيع رئيس دائرة التنظيم، ومصادقة المكتب التنفيذي لمجلس مدينة حماة.",
    fieldsDictionary: [
      {
        name: "اسم مقدم الطلب",
        key: "applicant_name",
        type: "string",
        required: true,
        description: "اسم مالك العقار الملاصق الراغب في شراء الفضلة.",
        validationRule: "نص عربي لا يقل عن 6 أحرف.",
        example: "خالد عبد الرحمن النجار",
      },
      {
        name: "رقم الهاتف الجوال",
        key: "mobile_number",
        type: "phone",
        required: true,
        description: "رقم الهاتف الجوال للتواصل وتنسيق موعد الكشف الميداني.",
        validationRule: "رقم سوري صالح مكون من 10 أرقام.",
        example: "0933987654",
      },
      {
        name: "رقم العقار الملاصق",
        key: "adjacent_property_number",
        type: "number",
        required: true,
        description: "الرقم العقاري للعقار الأصلي العائد لمقدم الطلب والملاصق للفضلة.",
        validationRule: "رقم صحيح موجب مسجل بالمنطقة العقارية.",
        example: "845",
      },
      {
        name: "اسم المنطقة العقارية",
        key: "cadastral_zone",
        type: "select",
        required: true,
        description: "المنطقة العقارية التي تقع ضمنها الفضلة والعقار الملاصق.",
        validationRule: "اختيار من قائمة المناطق العقارية المعتمدة.",
        example: "غرب المشتل",
      },
      {
        name: "وصف موقع الفضلة والمساحة التقديرية",
        key: "surplus_description",
        type: "string",
        required: true,
        description: "وصف طبوغرافي لموقع الفضلة وحدودها والمساحة التقريبية بالأمتار المربعة.",
        validationRule: "نص لا يقل عن 15 حرفاً يوضح الموقع والحدود الأربعة.",
        example: "فضلة مثلثة الشكل تقع شمال العقار 845 بمساحة تقريبية 18.5 م2 تطل على شارع 12م.",
      },
    ],
    validationConstraints: [
      {
        rule: "عدم قابلية الفضلة للبناء المنفرد كعقار مستقل",
        rationale: "إذا كانت مساحة وأبعاد الفضلة تؤهلها لتكون مقسماً مستقلاً، تعرض بالمزاد العلني ولا تباع لمالك الجوار بالمفاضلة.",
        severity: "error",
      },
      {
        rule: "انعدام أي نفع عام حالي أو مستقبلي للوحدة الإدارية",
        rationale: "التحقق من عدم حاجة البلدية للفضلة في توسيع شوارع أو مرافق بنية تحتية أو حدائق عامة.",
        severity: "error",
      },
      {
        rule: "حق الشفعة لجميع الجوار الملاصقين",
        rationale: "في حال وجود أكثر من عقار ملاصق لنفس الفضلة، يجب إخطار جميع المالكين رسمياً.",
        severity: "warning",
      },
    ],
    attachmentsSpecification: [
      {
        name: "بيان قيد عقاري حديث للعقار الملاصق",
        format: "PDF / JPEG",
        maxSize: "5MB",
        isRequired: true,
        purpose: "إثبات صفة المالك الملاصق للفضلة.",
        issuingAuthority: "السجل العقاري بحماة",
      },
      {
        name: "مخطط كروكي ومساحي معتمد بإحداثيات GIS",
        format: "PDF / DWG",
        maxSize: "15MB",
        isRequired: true,
        purpose: "تحديد إحداثيات الفضلة وأبعادها الهندسية والمساحة الدقيقة.",
        issuingAuthority: "شعبة أمانة الخارطة أو مهندس مساحة معتمد",
      },
      {
        name: "صور فوتوغرافية واضحة لموقع الفضلة والعقار",
        format: "JPEG / PNG",
        maxSize: "10MB",
        isRequired: true,
        purpose: "إيضاح واقع الحال والإشغالات الحالية الميدانية.",
        issuingAuthority: "مقدم الطلب أو المهندس المشرف",
      },
    ],
    edgeCasesAndReturns: [
      {
        condition: "ظهور نزاع حول حدود الفضلة مع جوار آخر ملاصق",
        action: "تجميد إجراءات البيع وتوجيه إخطارات رسمية للطرفين أو إحالة الإضبارة إلى اللجنة الفنية المشتركة.",
        returnCode: "ERR_BOUNDARY_DISPUTE",
      },
      {
        condition: "وجود شبكات بنية تحتية (مياه، صرف صحي، كابلات كهربائية) تمر بالفضلة",
        action: "طلب كشوف فنية من مؤسسات المرافق العامة لتحديد تكلفة وشروط النقل أو رفض البيع.",
        returnCode: "ERR_UTILITY_INTERFERENCE",
      },
    ],
    apiPayloadExample: JSON.stringify(
      {
        service_id: "purchase-surplus",
        applicant: {
          name: "خالد عبد الرحمن النجار",
          phone: "0933987654",
        },
        target_property: {
          adjacent_number: 845,
          cadastral_zone: "غرب المشتل",
          estimated_area_sqm: 18.5,
        },
        documents: [
          { type: "CADASTRAL_RECORD", file_id: "rec_845.pdf" },
          { type: "SURVEY_MAP_COORDS", file_id: "surplus_map_845.dwg" },
        ],
      },
      null,
      2
    ),
    faqs: [
      {
        id: "faq-surplus-01",
        category: "إداري وتشغيلي",
        question: "ما هي المراحل الإدارية المتبعة لتسعير واعتماد بيع الفضلة؟",
        answer: "تشكل لجنة تقدير فنية وفق القرار الوزاري تضم مندوباً مالياً ومهندس تنظيم وممثل دائرة الأملاك، وتجري كشفاً حسياً، ثم يصاغ المحضر ويوضع السعر الرائج، ويعرض على المكتب التنفيذي لمجلس المدينة للإقرار النهائي.",
      },
      {
        id: "faq-surplus-02",
        category: "تقني ونموذج البيانات",
        question: "كيف يعالج النظام التقاطعات المكانية للفضلة مع خطوط التنظيم؟",
        answer: "يقوم محرك الخرائط بمطابقة مضلع الفضلة (Vector Polygon) مع طبقة الشوارع التنظيمية (Road Alignment Layer) والمرافق العامة، وإذا حدث تداخل مساحي، يولد النظام تلقائياً إشعار اعتراض للجنة التنظيم.",
      },
      {
        id: "faq-surplus-03",
        category: "مالي وقانوني",
        question: "هل يعتبر تقديم الطلب التزاماً من البلدية بإتمام البيع؟",
        answer: "لا، تقديم الطلب هو إجراء استطلاعي واستعلامي لدراسة الوضع التنظيمي والمكاني، ويحق للبلدية رفض البيع إذا اقتضت مصلحة المخطط التنظيمي العام ذلك.",
      },
      {
        id: "faq-surplus-04",
        category: "إجراءات واعتمادات",
        question: "ما هو الإجراء في حال اعتراض أحد الجيران على ضم الفضلة؟",
        answer: "يعطى المعترض مهلة نظامية قدرها 15 يوماً لتقديم وثائق تثبت ملاصقته واستعداده للمشاركة بالشراء، وإلا يتم البت في المعاملة للمتقدم الأصلي طبقاً للأولوية المكانية.",
      },
    ],
  },

  "property-croquis": {
    serviceId: "property-croquis",
    serviceCode: "SRV-URB-003",
    legalBasis: "القرار الوزاري المنظم لإصدار المخططات الطبوغرافية والتنظيمية وجداول الرسوم البلدية المعتمدة لعام 2024.",
    slaDays: 2,
    slaDescription: "بين 1 إلى 3 أيام عمل رسمية من تاريخ تسجيل الطلب واستيفاء الوثائق المطلوبة والتدقيق الفني.",
    businessGoal: "إصدار مخطط طبوغرافي هندسي دقيق (كروكي) يوضح موقع العقار وحدوده وشوارعه والارتدادات التنظيمية لتقديمه في المعاملات الرسمية.",
    targetBeneficiary: "المواطنون، المكاتب الهندسية، البنوك، الدوائر الحكومية والمحاكم.",
    digitalMaturityLevel: "إجراء هجين ورقي/رقمي",
    deliverableType: "مخطط كروكي رسمي ملون موقع ومختوم بالختم النافر مع باركود تحقق رقمي ومخطط الموقع العام.",
    officialCertification: "توقيع الرسامة المدققة، رئيس شعبة أمانة الخارطة، رئيس دائرة التخطيط العمراني، ومصادقة مدير المدينة.",
    fieldsDictionary: [
      {
        name: "اسم مقدم الطلب",
        key: "applicant_name",
        type: "string",
        required: true,
        description: "اسم المستفيد أو المهندس المفوض باستلام الكروكي.",
        validationRule: "نص عربي لا يقل عن 5 أحرف.",
        example: "سامر توفيق الأحمد",
      },
      {
        name: "محل إقامة مقدم الطلب",
        key: "applicant_residence",
        type: "string",
        required: true,
        description: "عنوان السكن الحالي بالتفصيل للتواصل الرسمي.",
        validationRule: "نص تفصيلي يشمل الحي والشارع.",
        example: "حماة - الصابونية - شارع المتنبي",
      },
      {
        name: "رقم العقار",
        key: "property_number",
        type: "number",
        required: true,
        description: "الرقم المساحي للعقار المراد إصدار الكروكي له.",
        validationRule: "رقم صحيح موجب.",
        example: "5023",
      },
      {
        name: "اسم المنطقة العقارية",
        key: "cadastral_zone",
        type: "select",
        required: true,
        description: "المنطقة العقارية التابع لها العقار.",
        validationRule: "قيمة معتمدة من جدول المناطق.",
        example: "الشريعة",
      },
      {
        name: "التكليف المساحي مع إحداثيات X وY",
        key: "coordinates_survey",
        type: "coordinates",
        required: true,
        description: "إحداثيات جغرافية بنظام UTM أو الإحداثيات السورية المعتمدة لنقاط أركان العقار.",
        validationRule: "إحداثيات مطابقة للشبكة الجيوديسية لبلدية حماة مع دقة خطأ لا تتجاوز 5 سم.",
        example: "X: 35.13124, Y: 36.75841",
      },
    ],
    validationConstraints: [
      {
        rule: "مطابقة التكليف المساحي للشبكة المرجعية",
        rationale: "ضرورة ربط الإحداثيات بنقاط الثوابت المساحية التابعة للبلدية لضمان عدم إزاحة المخطط.",
        severity: "error",
      },
      {
        rule: "تسديد الرسوم المالية المعتمدة (9700 ليرة سورية قديمة)",
        rationale: "لا تصدر المخططات ولا توقع دون إرفاق إشعار القبض المالي الصادر عن الصندوق المالي للبلدية.",
        severity: "error",
      },
    ],
    attachmentsSpecification: [
      {
        name: "إشعار تسديد الرسوم المالية (9700 ليرة سورية قديمة)",
        format: "PDF / JPEG",
        maxSize: "3MB",
        isRequired: true,
        purpose: "إثبات سداد بدل خدمة إعداد الكروكي والرسوم البلدية المقررة.",
        issuingAuthority: "صندوق بلدية مدينة حماة",
      },
      {
        name: "التكليف المساحي وجدول الإحداثيات المعتمد",
        format: "PDF / CSV",
        maxSize: "5MB",
        isRequired: true,
        purpose: "استيراد النقاط ورسم حدود العقار بدقة في بيئة CAD/GIS.",
        issuingAuthority: "مساح مرخص بنقابة المهندسين",
      },
      {
        name: "سند الملكية أو بيان القيد العقاري",
        format: "PDF",
        maxSize: "5MB",
        isRequired: false,
        purpose: "التحقق من صحة الرقم العقاري والمنطقة.",
        issuingAuthority: "المصالح العقارية",
      },
    ],
    edgeCasesAndReturns: [
      {
        condition: "تعارض الإحداثيات المدخلة مع حدود عقار مجاور على المخطط العام",
        action: "إعادة الطلب للرسام المساحي للتدقيق الميداني وإشعار المتقدم بوجود تداخل حدودي.",
        returnCode: "ERR_COORDINATES_OVERLAP",
      },
      {
        condition: "عدم وضوح مدخل العقار أو الشارع المؤدي إليه في المخطط التنظيمي",
        action: "إحالة الملف إلى مهندس الشعبة لإجراء مطابقة مع المخطط التفصيلي المصدق.",
        returnCode: "ERR_ACCESS_UNCLEAR",
      },
    ],
    apiPayloadExample: JSON.stringify(
      {
        service_id: "property-croquis",
        applicant: {
          name: "سامر توفيق الأحمد",
          residence: "حماة - الصابونية",
          phone: "0955112233",
        },
        property: {
          number: 5023,
          zone: "الشريعة",
          coordinates: [
            { point: "P1", x: 35.13124, y: 36.75841 },
            { point: "P2", x: 35.13148, y: 36.75842 },
            { point: "P3", x: 35.13149, y: 36.75815 },
            { point: "P4", x: 35.13125, y: 36.75814 },
          ],
        },
        fee_receipt: {
          receipt_no: "REC-2026-9812",
          amount: 9700,
          currency: "SYP",
        },
      },
      null,
      2
    ),
    faqs: [
      {
        id: "faq-croquis-01",
        category: "إداري وتشغيلي",
        question: "ما هي المدة الزمنية لصلاحية مخطط الكروكي الفني الصادر؟",
        answer: "يعتبر الكروكي صالحاً لمدة سنة واحدة من تاريخ إصداره ما لم يطرأ تعديل رسمي على المخطط التنظيمي العام أو التفصيلي للمنطقة.",
      },
      {
        id: "faq-croquis-02",
        category: "تقني ونموذج البيانات",
        question: "ما هي صيغ التصدير الرقمية المعتمدة لنقاط ومخطط الكروكي؟",
        answer: "يتم حفظ المخطط بصيغتي DXF/DWG للأنظمة الهندسية وبصيغة PDF ممهورة بختم رقمي مشفر (QR Code) يحتوي رابط التحقق التلقائي.",
      },
      {
        id: "faq-croquis-03",
        category: "مالي وقانوني",
        question: "هل يشمل رسم الـ 9700 ليرة سورية قديمة الكشف الميداني في حال لزومه؟",
        answer: "الرسم يغطي أعمال السحب والتدقيق الأوتوكادي المكتبي، وفي حال الحاجة إلى لجنة كشف طبوغرافي ميداني خارجي يضاف بدل انتقال وفق اللائحة المالية.",
      },
      {
        id: "faq-croquis-04",
        category: "إجراءات واعتمادات",
        question: "من هي الجهة صاحبة الاختصاص بالتوقيع النهائي على الكروكي؟",
        answer: "يوقع المخطط من المهندسة الرسامة والمدققة ورئيس شعبة أمانة الخارطة، وتتم المصادقة الرسمية والختم من قبل مدير المدينة ورئيس دائرة التخطيط.",
      },
    ],
  },

  "regulatory-status": {
    serviceId: "regulatory-status",
    serviceCode: "SRV-URB-004",
    legalBasis: "قانون التخطيط العمراني، المخطط التنظيمي العام المصدق لمدينة حماة ونظام الارتفاقات المعمارية.",
    slaDays: 2,
    slaDescription: "بين 1 إلى 3 أيام عمل رسمية من تاريخ تسجيل الطلب واستيفاء الوثائق المطلوبة والتدقيق الفني.",
    businessGoal: "تزويد صاحب العلاقة ببيان رسمي يبين الصفة التنظيمية للعقار، نظام البناء المسموح، الارتفاقات، وتوسعات الشوارع المستحدثة.",
    targetBeneficiary: "المواطنون، المستثمرون العقاريون، الشركات، والمكاتب الهندسية قبل إعداد المشاريع.",
    digitalMaturityLevel: "مكتمل رقمياً",
    deliverableType: "وثيقة بيان وضع تنظيمي رسمي معتمد متضمنة جدول الارتفاقات وعامل الاستثمار والاشتراطات.",
    officialCertification: "توقيع رئيس شعبة التخطيط والتنظيم ورئيس دائرة التخطيط العمراني مع خاتم الدائرة.",
    fieldsDictionary: [
      {
        name: "اسم مقدم الطلب",
        key: "applicant_name",
        type: "string",
        required: true,
        description: "اسم المستعلم أو المفوض بالاستعلام التنظيمي.",
        validationRule: "نص عربي صحيح.",
        example: "مروان عدنان البيطار",
      },
      {
        name: "رقم الهاتف الجوال",
        key: "mobile_number",
        type: "phone",
        required: true,
        description: "رقم الجوال لإرسال إشعار جاهزية التقرير التنظيمي.",
        validationRule: "رقم خلوي سوري 10 أرقام.",
        example: "0966442211",
      },
      {
        name: "رقم العقار",
        key: "property_number",
        type: "number",
        required: true,
        description: "رقم العقار المستعلم عن وضعه التنظيمي.",
        validationRule: "رقم صحيح إيجابي.",
        example: "3114",
      },
      {
        name: "اسم المنطقة العقارية",
        key: "cadastral_zone",
        type: "select",
        required: true,
        description: "المنطقة العقارية الواقع ضمنها العقار.",
        validationRule: "قيمة من قائمة المناطق المعتمدة.",
        example: "المرابط",
      },
      {
        name: "نص الاستعلام والغرض من الاستفسار",
        key: "inquiry_details",
        type: "string",
        required: true,
        description: "شرح الاستفسار المطلوب (مثل عدد الطوابق المسموحة، نوع الاستخدام، خطوط التنظيم والارتدادات).",
        validationRule: "نص لا يقل عن 10 أحرف.",
        example: "استعلام عن الصفة التنظيمية ونسبة البناء وارتفاع الطوابق المسموح به ووجود أي استملاك نافذ.",
      },
    ],
    validationConstraints: [
      {
        rule: "وقوع العقار ضمن الحدود الإدارية والتنظيمية لمجلس مدينة حماة",
        rationale: "إذا كان العقار يقع في منطقة حماية خارج المخطط أو تابع للخدمات الفنية بالمحافظة، يحال الطلب للجهة المختصة.",
        severity: "error",
      },
      {
        rule: "دقة تحديد رقم العقار والمنطقة لتجنب تداخل المقاسم",
        rationale: "التأكد من عدم وجود تشابه أرقام بين المناطق العقارية المختلفة (مثل الحاضر والمدينة).",
        severity: "error",
      },
    ],
    attachmentsSpecification: [
      {
        name: "صورة عن بيان القيد العقاري",
        format: "PDF / JPEG",
        maxSize: "5MB",
        isRequired: false,
        purpose: "الاستئناس بالبيانات العقارية والأوصاف المدونة بالصحيفة.",
        issuingAuthority: "السجل العقاري",
      },
      {
        name: "مخطط موقع أو كروكي استرشادي",
        format: "PDF / JPEG",
        maxSize: "5MB",
        isRequired: false,
        purpose: "تسهيل إسقاط العقار على الخريطة التنظيمية التفاعلية.",
        issuingAuthority: "مقدم الطلب",
      },
    ],
    edgeCasesAndReturns: [
      {
        condition: "وقوع العقار في منطقة قيد الدراسة التعديلية للمخطط التنظيمي",
        action: "تدوين ملاحظة في البيان بأن المنطقة تخضع لتعديل تنظيمي قيد التصديق وإرفاق رقم قرار التجميد إن وجد.",
        returnCode: "WRN_PLAN_UNDER_REVISION",
      },
      {
        condition: "مرور خط نفع عام (سكة حديد، حرم خطوط توتر عالي، خط غاز) بمحيط العقار",
        action: "تضمين مسافات الحرم والارتفاق الإجباري الصادر عن الوزارات المعنية ضمن البيان.",
        returnCode: "INFO_SPECIAL_EASEMENT",
      },
    ],
    apiPayloadExample: JSON.stringify(
      {
        service_id: "regulatory-status",
        applicant: {
          name: "مروان عدنان البيطار",
          phone: "0966442211",
        },
        query: {
          property_number: 3114,
          cadastral_zone: "المرابط",
          scope: ["ZONING_CATEGORY", "MAX_FLOORS", "SETBACKS", "EXPROPRIATION_CHECK"],
        },
      },
      null,
      2
    ),
    faqs: [
      {
        id: "faq-reg-01",
        category: "إداري وتشغيلي",
        question: "هل يعتد ببيان الوضع التنظيمي كرخصة بناء أو إذن صب؟",
        answer: "كلا، بيان الوضع التنظيمي هو وثيقة إعلامية وتخطيطية تبين نظام المنطقة والارتفاقات فقط، ولا يغني عن استصدار رخصة بناء نظامية وفق الإجراءات القانونية.",
      },
      {
        id: "faq-reg-02",
        category: "تقني ونموذج البيانات",
        question: "كيف يستخرج النظام المعلومات التنظيمية آلياً؟",
        answer: "يقوم النظام باستعلام طبقات نظم المعلومات الجغرافية (GIS Spatial Query) ومقاطعة نقطة العقار مع مضلع المنطقة التنظيمية، واسترجاع ضوابط البناء (عامل الاستثمار، الارتفاع، الردود، والصفة) تلقائياً.",
      },
      {
        id: "faq-reg-03",
        category: "مالي وقانوني",
        question: "هل توجد رسوم مالية للاستعلام عن الوضع التنظيمي؟",
        answer: "الخدمة الاستعلامية الإلكترونية متاحة مجاناً عبر المنصة، أما في حال طلب وثيقة ورقية مصدقة ومختومة رسمياً فيسدد رسم الطابع البلدي المقرر.",
      },
      {
        id: "faq-reg-04",
        category: "إجراءات واعتمادات",
        question: "ماذا يحدث إذا كان المخطط التفصيلي للمنطقة غير مكتمل؟",
        answer: "تتم إحالة الطلب إلى شعبة التخطيط العمراني لدراسة الحالة الفردية والاعتماد على الضابطة العامة للمنطقة المحيطة وإصدار بيان مؤقت.",
      },
    ],
  },

  "change-property-use": {
    serviceId: "change-property-use",
    serviceCode: "SRV-URB-005",
    legalBasis: "قانون التنظيم والتطوير العمراني رقم 23/2015، وقرارات المجلس البلدي المحددة للمحاور والفعاليات التجارية والخدمية.",
    slaDays: 2,
    slaDescription: "بين 1 إلى 3 أيام عمل رسمية من تاريخ تسجيل الطلب واستيفاء الوثائق المطلوبة والتدقيق الفني.",
    businessGoal: "دراسة إمكانية تحويل الاستخدام المعتمد للعقار (مثلاً من سكني إلى تجاري أو مهني أو تعليمي) والتأكد من توافقه مع المخطط التنظيمي.",
    targetBeneficiary: "أصحاب العقارات الراغبون في استثمار عقاراتهم بأنشطة وفعاليات غير سكنية.",
    digitalMaturityLevel: "إجراء هجين ورقي/رقمي",
    deliverableType: "بيان رأي تنظيمي أولي بالموافقة المشروطة أو الرفض المعلل مع جدول متطلبات الترخيص الإداري.",
    officialCertification: "توقيع رئيس شعبة التخطيط، رئيس دائرة التنظيم والتخطيط العمراني، ومصادقة اللجنة العمرانية.",
    fieldsDictionary: [
      {
        name: "اسم مقدم الطلب",
        key: "applicant_name",
        type: "string",
        required: true,
        description: "اسم مالك العقار أو المستثمر المفوض.",
        validationRule: "نص عربي ثلاثي.",
        example: "هشام وليد طيفور",
      },
      {
        name: "رقم الهاتف الجوال",
        key: "mobile_number",
        type: "phone",
        required: true,
        description: "رقم هاتف لمتابعة الإجراءات ومواعيد الكشف.",
        validationRule: "10 أرقام سورية.",
        example: "0988776655",
      },
      {
        name: "رقم العقار",
        key: "property_number",
        type: "number",
        required: true,
        description: "الرقم المساحي للعقار المطلوب تغيير استخدامه.",
        validationRule: "رقم صحيح موجب.",
        example: "1940",
      },
      {
        name: "الاستخدام الحالي للعقار",
        key: "current_usage",
        type: "select",
        required: true,
        description: "الصفة الحالية المثبتة في القيد ورخصة البناء.",
        validationRule: "قيمة من قائمة: [سكني، تجاري، مستودع، مهني، خدمات].",
        example: "سكني",
      },
      {
        name: "الاستخدام المقترح",
        key: "proposed_usage",
        type: "select",
        required: true,
        description: "النشاط أو الاستخدام الجديد المراد تحويل العقار إليه.",
        validationRule: "قيمة من قائمة الفعاليات التنظيمية المعتمدة.",
        example: "تجاري (مكاتب إدارية وخدمية)",
      },
      {
        name: "مبررات طلب التغيير والوصف التفصيلي",
        key: "justification",
        type: "string",
        required: true,
        description: "الأسباب التخطيطية والتجارية وموقع العقار بالنسبة للشوارع الرئيسية.",
        validationRule: "نص لا يقل عن 20 حرفاً.",
        example: "العقار يقع في الطابق الأرضي المطل على شارع بعرض 16م مدرج ضمن المحاور التجارية المقترحة بموجب قرار مجلس المدينة.",
      },
    ],
    validationConstraints: [
      {
        rule: "توافق الشارع المطل عليه العقار مع نظام المحاور التجارية",
        rationale: "لا يجوز تحويل الاستخدام لفعاليات تجارية ضمن الشوارع السكنية الضيقة (أقل من العرض النظامي المحدد).",
        severity: "error",
      },
      {
        rule: "توفير المواقف والاشتراطات البيئية والسلامة",
        rationale: "التحقق من عدم تسبب النشاط الجديد في إزعاج الجوار أو خلق اختناقات مرورية.",
        severity: "warning",
      },
      {
        rule: "موافقة شاغلي البناء المشترك في الملكية الطابقية",
        rationale: "وفق نظام إدارة البناء المشترك، يتطلب تغيير الصفة السكنية لبعض الفعاليات موافقة جمعية المالكين.",
        severity: "warning",
      },
    ],
    attachmentsSpecification: [
      {
        name: "بيان قيد عقاري حديث ورخصة البناء القائمة",
        format: "PDF / JPEG",
        maxSize: "5MB",
        isRequired: true,
        purpose: "التحقق من الصفة الأصلية المرخصة والمساحات المعتمدة.",
        issuingAuthority: "دائرة الرخص والمصالح العقارية",
      },
      {
        name: "مخطط كروكي وموقع عام للبناء والشوارع المحيطة",
        format: "PDF / DWG",
        maxSize: "10MB",
        isRequired: true,
        purpose: "دراسة عرض الشارع وموقع المداخل والمخارج والارتدادات.",
        issuingAuthority: "مهندس معتمد",
      },
      {
        name: "دراسة ومخطط النشاط المقترح والتوزيع الداخلي",
        format: "PDF",
        maxSize: "10MB",
        isRequired: true,
        purpose: "التحقق من ملاءمة التوزيع الداخلي لاشتراطات الفعالية الجديدة.",
        issuingAuthority: "مكتب هندسي استشاري",
      },
    ],
    edgeCasesAndReturns: [
      {
        condition: "الشارع المطل عليه العقار سكني صرف ولا يقع على محور تجاري",
        action: "إصدار قرار اعتذار تنظيمي معلل بعدم توافق الطلب مع ضابطة البناء وتوجيه المتقدم إلى المناطق المسموحة.",
        returnCode: "ERR_ZONING_INCOMPATIBLE",
      },
      {
        condition: "الفعالية المقترحة مصنفة كمهنة مقلقة للراحة أو ضارة بالصحة",
        action: "اشتراط الحصول على موافقة مديرية البيئة ولجنة التراخيص الصناعية قبل استكمال المعاملة.",
        returnCode: "REQ_ENV_CLEARANCE",
      },
    ],
    apiPayloadExample: JSON.stringify(
      {
        service_id: "change-property-use",
        applicant: {
          name: "هشام وليد طيفور",
          phone: "0988776655",
        },
        property_id: 1940,
        cadastral_zone: "دوار الفراية",
        current_type: "RESIDENTIAL",
        requested_type: "COMMERCIAL_OFFICES",
        street_width_m: 16.0,
      },
      null,
      2
    ),
    faqs: [
      {
        id: "faq-change-01",
        category: "إداري وتشغيلي",
        question: "هل يعتبر الرأي التنظيمي الإيجابي كافياً لممارسة النشاط التجاري فوراً؟",
        answer: "كلا، الموافقة التنظيمية هي خطوة تمهيدية تثبت ملاءمة الموقع تخطيطياً، ويليها استصدار رخصة تعديل بناء ورخصة فتح ومزاولة مهنة من دائرة الرخص والشؤون الصحية.",
      },
      {
        id: "faq-change-02",
        category: "تقني ونموذج البيانات",
        question: "ما هي المتغيرات الحسابية التي يفحصها النظام للموافقة على التغيير؟",
        answer: "يقيس النظام عرض الشارع الموثق في طبقة الشبكة الطرقية، ويتحقق من تصنيف المنطقة العقارية، ومطابقة النشاط المقترح مع مصفوفة الفعاليات المسموحة في نظام ضابطة البناء.",
      },
      {
        id: "faq-change-03",
        category: "مالي وقانوني",
        question: "ما هي الالتزامات المالية الناتجة عن تغيير صفة العقار إلى تجاري؟",
        answer: "يترتب سداد رسم تحويل استخدام، وفروقات رسوم خدمات واستثمار وفق القوانين المالية للوحدات الإدارية بناء على المساحة المحولة.",
      },
      {
        id: "faq-change-04",
        category: "إجراءات واعتمادات",
        question: "هل يحق للجوار الطعن في الموافقة على تغيير الاستخدام؟",
        answer: "نعم، يحق لأصحاب الحقوق المتأثرين تقديم اعتراض رسمي خلال 15 يوماً من تاريخ نشر أو إعلان الموافقة للنظر فيه من قبل لجنة الاعتراضات العمرانية.",
      },
    ],
  },

  "preliminary-subdivision-approval": {
    serviceId: "preliminary-subdivision-approval",
    serviceCode: "SRV-URB-006",
    legalBasis: "قانون تنظيم وتوزيع المقاسم، وقانون الفرز الطابقي رقم 33 لعام 2008، ونظام البناء لمدينة حماة.",
    slaDays: 2,
    slaDescription: "بين 1 إلى 3 أيام عمل رسمية من تاريخ تسجيل الطلب واستيفاء الوثائق المطلوبة والتدقيق الفني.",
    businessGoal: "إعطاء موافقة مبدئية هندسية لدراسة فرز عقار إلى عدة مقاسم أو فرز طابقي لوحدات سكنية وتجارية قبل اعتماد المخططات الإفرازية النهائية.",
    targetBeneficiary: "شركات التطوير العقاري، المكاتب الهندسية، والمالكون على الشيوع الراغبون بالفرز الرضائي.",
    digitalMaturityLevel: "إجراء هجين ورقي/رقمي",
    deliverableType: "وثيقة موافقة مبدئية مشروطة معتمدة مع جدول اشتراطات الإفراز والحد الأدنى لواجهات ومساحات المقاسم.",
    officialCertification: "توقيع رئيس شعبة تنظيم المخططات الاستملاكية والإفراز، رئيس دائرة التنظيم، ومصادقة مدير الشؤون الفنية.",
    fieldsDictionary: [
      {
        name: "اسم مقدم الطلب",
        key: "applicant_name",
        type: "string",
        required: true,
        description: "اسم ممثل المالكين أو المكتب الهندسي المصمم للمشروع.",
        validationRule: "نص عربي لا يقل عن 6 أحرف.",
        example: "المهندس فراس نادر الكيلاني",
      },
      {
        name: "رقم الهاتف الجوال",
        key: "mobile_number",
        type: "phone",
        required: true,
        description: "رقم الجوال للمتابعة الفنية.",
        validationRule: "10 أرقام سورية.",
        example: "0944883322",
      },
      {
        name: "رقم العقار الأم",
        key: "parent_property_number",
        type: "number",
        required: true,
        description: "رقم العقار الأصلي المراد إفرازه.",
        validationRule: "رقم صحيح موجب مسجل بالمنطقة.",
        example: "2760",
      },
      {
        name: "نوع الإفراز المطلوب",
        key: "subdivision_type",
        type: "select",
        required: true,
        description: "طبيعة مشروع الإفراز (إفراز مقاسم أرضية، إفراز طابقي، إفراز جوار).",
        validationRule: "قيمة من قائمة: [إفراز طابقي، إفراز مقاسم مستقلة، إفراز جوار وتعديل حدود].",
        example: "إفراز طابقي",
      },
      {
        name: "عدد الوحدات أو المقاسم المقترحة",
        key: "proposed_units_count",
        type: "number",
        required: true,
        description: "إجمالي عدد المقاسم أو الشقق الناتجة عن مشروع الإفراز.",
        validationRule: "عدد صحيح أكبر من أو يساوي 2.",
        example: "12",
      },
      {
        name: "وصف المشروع والمساحة الإجمالية",
        key: "project_description",
        type: "string",
        required: true,
        description: "ملخص المشروع الإنشائي، عدد الطوابق، والمساحة الإجمالية للعقار.",
        validationRule: "نص لا يقل عن 25 حرفاً.",
        example: "مشروع برج سكني تجاري مؤلف من 6 طوابق بمساحة أرضية 850 م2 يتضمن 12 شقة ومستودعين ومواقف سيارات.",
      },
    ],
    validationConstraints: [
      {
        rule: "تحقيق الحد الأدنى لمساحة وواجهة المقسم الناتج",
        rationale: "لا يسمح بإفراز مقاسم أرضية تقل أبعادها أو مساحاتها عن المعايير التخطيطية المعتمدة للمنطقة.",
        severity: "error",
      },
      {
        rule: "تأمين المنافذ والارتفاقات المشتركة ومواقف السيارات",
        rationale: "في الإفراز الطابقي، يجب ضمان وصول كل وحدة إلى الدرج والمصعد والشارع العام مع توفير مواقف مطابقة لعدد الوحدات.",
        severity: "error",
      },
      {
        rule: "خلو العقار من إشارات الدعاوى العقارية غير المحسومة",
        rationale: "التأكد من موافقة جميع الشركاء على الشيوع لتفادي بطلان الفرز لاحقاً.",
        severity: "warning",
      },
    ],
    attachmentsSpecification: [
      {
        name: "بيان قيد عقاري حديث لكامل العقار الأم",
        format: "PDF / JPEG",
        maxSize: "5MB",
        isRequired: true,
        purpose: "التحقق من صحة الملكية والحصص السهمية لكافة المالكين.",
        issuingAuthority: "المصالح العقارية بحماة",
      },
      {
        name: "مخطط كروكي وتكليف مساحي طبوغرافي",
        format: "PDF / DWG",
        maxSize: "15MB",
        isRequired: true,
        purpose: "تطابق الحدود الإجمالية والمساحة السطحية مع الواقع التنظيمي.",
        issuingAuthority: "نقابة المهندسين / أمانة الخارطة",
      },
      {
        name: "المخططات المعمارية الإفرازية الأولية والمقاطع",
        format: "PDF / DWG",
        maxSize: "20MB",
        isRequired: true,
        purpose: "تدقيق المساحات المشتركة والخاصة والمناور والارتدادات والأقسام المفرزة.",
        issuingAuthority: "مكتب هندسي معتمد",
      },
    ],
    edgeCasesAndReturns: [
      {
        condition: "عدم كفاية مساحات المناور والإنارة الطبيعية لبعض الشقق المفرزة",
        action: "إعادة المخطط إلى المكتب الهندسي المصمم لتعديل المساقط المعمارية وتحقيق شروط الكود السوري للبناء.",
        returnCode: "ERR_LIGHTING_VENTILATION",
      },
      {
        condition: "وجود نقص في عدد مواقف السيارات الإلزامية في طابق القبو",
        action: "إلزام المطور بتوفير حلول هندسية بديلة أو دفع بدلات الموقف النظامية في حال إجازتها قانوناً.",
        returnCode: "ERR_PARKING_SHORTAGE",
      },
    ],
    apiPayloadExample: JSON.stringify(
      {
        service_id: "preliminary-subdivision-approval",
        applicant: {
          name: "فراس نادر الكيلاني",
          role: "CONSULTING_ENGINEER",
          phone: "0944883322",
        },
        property: {
          parent_number: 2760,
          zone: "جنوب الملعب",
          total_area_sqm: 850,
          subdivision_type: "FLOOR_SUBDIVISION",
          units_count: 12,
        },
      },
      null,
      2
    ),
    faqs: [
      {
        id: "faq-sub-01",
        category: "إداري وتشغيلي",
        question: "ما الفرق بين الموافقة المبدئية والمصادقة الإفرازية النهائية؟",
        answer: "الموافقة المبدئية تسمح بمتابعة إعداد الإضبارة التنفيذية والمخططات التفصيلية، بينما المصادقة النهائية هي التي تحال رسمياً إلى السجل العقاري لترقيم المقاسم وإصدار سندات الملكية المستقلة.",
      },
      {
        id: "faq-sub-02",
        category: "تقني ونموذج البيانات",
        question: "كيف يتم التحقق من مجموع مساحات الأجزاء المفرزة مقارنة بمساحة العقار الأم؟",
        answer: "يقوم النظام بإجراء عملية تدقيق حسابية آلية (Sum of Partitions Area vs Parent Area) للتحقق من أن مجموع مساحات المقاسم والوجائب والمنافع المشتركة يساوي تماماً المساحة الإجمالية المقيدة للعقار مع مراعاة نسب التسامح المساحية.",
      },
      {
        id: "faq-sub-03",
        category: "مالي وقانوني",
        question: "هل يلزم سداد رسوم تحسين على المقاسم المفرزة؟",
        answer: "تخضع المقاسم الناتجة لقوانين الرسوم البلدية والفرز، وتحدد بدلات التحسين إن وجدت وفقاً لقرار لجنة التقييم المعتمدة.",
      },
      {
        id: "faq-sub-04",
        category: "إجراءات واعتمادات",
        question: "ما هي اللجان التي يلزم مرور الإضبارة عليها قبل الاعتماد؟",
        answer: "تمر المعاملة عبر الشعبة الفنية للإفراز ودائرة التنظيم، وفي المشاريع الكبرى تحال إلى اللجنة العمرانية الفرعية للاعتماد.",
      },
    ],
  },

  "panoramic-elevators-inquiry": {
    serviceId: "panoramic-elevators-inquiry",
    serviceCode: "SRV-URB-007",
    legalBasis: "الكود السوري لسلامة وتركيب المصاعد والأدراج الكهربائية، وضوابط السلامة والواجهات المعمارية المعتمدة لدى بلدية حماة.",
    slaDays: 2,
    slaDescription: "بين 1 إلى 3 أيام عمل رسمية من تاريخ تسجيل الطلب واستيفاء الوثائق المطلوبة والتدقيق الفني.",
    businessGoal: "توضيح وتحديد الاشتراطات التنظيمية، الإنشائية، والجمالية الواجب توافرها قبل تركيب مصعد بانورامي خارجي أو داخلي على واجهات المباني.",
    targetBeneficiary: "مالكو العقارات السكنية والتجارية، لجان إدارة الأبنية، وشركات تركيب وصيانة المصاعد.",
    digitalMaturityLevel: "مكتمل رقمياً",
    deliverableType: "تقرير اشتراطات فنية استشاري موجه للمالك يبين محددات البروز والواجهة والحمولة وشروط الترخيص.",
    officialCertification: "توقيع مهندس التنظيم والواجهات، ورئيس دائرة التنظيم والتخطيط العمراني.",
    fieldsDictionary: [
      {
        name: "اسم مقدم الطلب",
        key: "applicant_name",
        type: "string",
        required: true,
        description: "اسم المالك أو ممثل لجنة إدارة البناء المشترك.",
        validationRule: "نص عربي لا يقل عن 5 أحرف.",
        example: "عمار رياض السعدي",
      },
      {
        name: "رقم الهاتف الجوال",
        key: "mobile_number",
        type: "phone",
        required: true,
        description: "رقم الهاتف المعتمد للتواصل التقني.",
        validationRule: "10 أرقام سورية.",
        example: "0933556677",
      },
      {
        name: "عنوان العقار والمنطقة",
        key: "property_address",
        type: "string",
        required: true,
        description: "العنوان التفصيلي للبناء القائم واسم الشارع والحي.",
        validationRule: "نص تفصيلي واضح.",
        example: "حماة - الكيلانية - شارع العاصي - بناء الأمل",
      },
      {
        name: "نوع المبنى القائم",
        key: "building_type",
        type: "select",
        required: true,
        description: "تصنيف طبيعة إشغال المبنى.",
        validationRule: "قيمة من قائمة: [سكني قائم، تجاري، مشفى/مركزي، منشأة سياحية].",
        example: "سكني قائم",
      },
      {
        name: "موقع المصعد المقترح ومسار البروز",
        key: "elevator_location_description",
        type: "string",
        required: true,
        description: "تحديد ما إذا كان المصعد على الواجهة الرئيسية، الواجهة الخلفية، أو ضمن المنور/البهو الداخلي.",
        validationRule: "نص لا يقل عن 15 حرفاً.",
        example: "برج معدني بانورامي على الواجهة الجانبية الغربية للبناء بارتفاع 5 طوابق داخل وجيبة الارتداد.",
      },
    ],
    validationConstraints: [
      {
        rule: "عدم التعدي على خط التنظيم وعرض الرصيف العام",
        rationale: "يمنع تماماً أن يشكل البروز الخارجي للمصعد إشغالاً للأملاك العامة أو تضييقاً للشارع أو رصيف المشاة.",
        severity: "error",
      },
      {
        rule: "سلامة الهيكل الإنشائي والتحمل الزلزالي",
        rationale: "اشتراط دراسة استناد وتثبيت البرج المعدني للواجهة من مهندس إنشائي مرخص لتفادي الإجهادات على المبنى القائم.",
        severity: "error",
      },
      {
        rule: "موافقة خطية من جميع مالكي الشقق المطلة على المنور أو الواجهة",
        rationale: "ضمان عدم حجب الرؤية أو الإنارة الطبيعية والتهوية عن الشقق المجاورة لمسار المصعد.",
        severity: "warning",
      },
    ],
    attachmentsSpecification: [
      {
        name: "مخطط الواجهة المعمارية للبناء مع مسار المصعد",
        format: "PDF / DWG",
        maxSize: "10MB",
        isRequired: true,
        purpose: "التحقق من تناسق المظهر الجمالي والأبعاد والبروز عن الواجهة.",
        issuingAuthority: "مهندس معماري مصمم",
      },
      {
        name: "تقرير فحص السلامة الإنشائية ومخطط التثبيت",
        format: "PDF",
        maxSize: "10MB",
        isRequired: true,
        purpose: "إثبات قدرة الجدران والأعمدة الحاملة على تحمل أحمال الهيكل وحركة الكبين.",
        issuingAuthority: "مكتب هندسي إنشائي معتمد",
      },
      {
        name: "صور فوتوغرافية حديثة لكامل واجهة المبنى",
        format: "JPEG / PNG",
        maxSize: "10MB",
        isRequired: true,
        purpose: "معاينة واقع الواجهة وأماكن النوافذ والشرفات القائمة.",
        issuingAuthority: "مقدم الطلب",
      },
    ],
    edgeCasesAndReturns: [
      {
        condition: "تداخل موقع المصعد مع شبكات خطوط المياه أو كابلات الكهرباء على الواجهة",
        action: "اشتراط تقديم مخطط تحويل الشبكات معتمد من مؤسسات الخدمة المعنية قبل الترخيص.",
        returnCode: "ERR_FACADE_SERVICES",
      },
      {
        condition: "حجب المصعد البانورامي لنوافذ غرف نوم رئيسية لشقق مجاورة",
        action: "رفض موقع التركيب وإلزام المتقدم بنقله إلى المنور أو زاوية مغلقة لا تضر بالإنارة النظامية.",
        returnCode: "ERR_LIGHTING_OBSTRUCTION",
      },
    ],
    apiPayloadExample: JSON.stringify(
      {
        service_id: "panoramic-elevators-inquiry",
        applicant: {
          name: "عمار رياض السعدي",
          phone: "0933556677",
        },
        building_info: {
          address: "حماة - الكيلانية",
          building_type: "RESIDENTIAL",
          floors_count: 5,
          elevator_position: "WEST_FACADE_SETBACK",
          glass_type: "LAMINATED_SAFETY_GLASS",
        },
      },
      null,
      2
    ),
    faqs: [
      {
        id: "faq-elev-01",
        category: "إداري وتشغيلي",
        question: "هل يحتاج تركيب المصعد البانورامي الخارجي إلى ترخيص بناء تعديلي؟",
        answer: "نعم، يعتبر إضافة المصعد الخارجي تعديلاً معمارياً وإنشائياً يستوجب استصدار رخصة تعديل واجهات وترخيص مصعد نظامي قبل بدء الأعمال التنفيذية.",
      },
      {
        id: "faq-elev-02",
        category: "تقني ونموذج البيانات",
        question: "ما هي المعايير الرقمية لزجاج وأمان المصاعد البانورامية المعتمدة؟",
        answer: "يشترط استخدام زجاج أمان متعدد الطبقات (Laminated Safety Glass) بسماكة لا تقل عن 10 مم، مع نظام هبوط اضطراري أوتوماتيكي ومكابح باراشوت مطابقة للمواصفة القياسية السورية للمصاعد.",
      },
      {
        id: "faq-elev-03",
        category: "مالي وقانوني",
        question: "من يتحمل المسؤولية القانونية عن صيانة المصعد وسلامة مستخدميه؟",
        answer: "تتحمل لجنة البناء والشركة المتعاقد معها للصيانة الدورية المسؤولية الكاملة، ويجب تجديد عقد الصيانة والتأمين بشكل سنوي وتقديم نسخة للدائرة.",
      },
      {
        id: "faq-elev-04",
        category: "إجراءات واعتمادات",
        question: "ما هو أقصى بروز مسموح به للمصعد عن استقامة الواجهة؟",
        answer: "يحدد البروز بما لا يتجاوز 1.20م شريطة بقائه بالكامل داخل حدود وجيبة الارتداد الأمامي النظامي للعقار وعدم التعدي على خط التنظيم.",
      },
    ],
  },

  "pharmacy-license": {
    serviceId: "pharmacy-license",
    serviceCode: "SRV-URB-007-PH",
    legalBasis: "قانون مزاولة المهن الطبية والصيدلانية، وضوابط وشروط الترخيص المكاني للمؤسسات الصيدلانية المعتمدة من وزارة الصحة ونقابة الصيادلة ومجلس مدينة حماة.",
    slaDays: 2,
    slaDescription: "بين 1 إلى 3 أيام عمل رسمية من تاريخ تسجيل الطلب واستيفاء الوثائق المطلوبة والتدقيق الفني.",
    businessGoal: "التحقق من استيفاء المحل التجاري للاشتراطات المكانية والتنظيمية والصحية اللازمة لترخيص وإشغال صيدلية وفق القانون.",
    targetBeneficiary: "الصيادلة المرخصون نظامياً والمسجلون في فرع نقابة الصيادلة بحماة.",
    digitalMaturityLevel: "إجراء هجين ورقي/رقمي",
    deliverableType: "كتاب مطابقة مكانية وتنظيمية وإحالة رسمية لمديرية الصحة وفرع نقابة الصيادلة لمنح الترخيص النهائي.",
    officialCertification: "توقيع مهندس الكشف، رئيس دائرة التنظيم والتخطيط العمراني، ومصادقة مدير الشؤون الفنية.",
    fieldsDictionary: [
      {
        name: "اسم مقدم الطلب (الصيدلي)",
        key: "pharmacist_name",
        type: "string",
        required: true,
        description: "الاسم الكامل للصيدلي طالب الترخيص.",
        validationRule: "نص عربي صحيح مطابق للهوية والشهادة المهنية.",
        example: "د. ريم بسام القنواتي",
      },
      {
        name: "رقم الهاتف الجوال",
        key: "mobile_number",
        type: "phone",
        required: true,
        description: "رقم الجوال الخاص بالصيدلي.",
        validationRule: "10 أرقام سورية.",
        example: "0955998877",
      },
      {
        name: "عنوان العقار والمحل المقترح",
        key: "pharmacy_address",
        type: "string",
        required: true,
        description: "العنوان التفصيلي للمحل (الحي، الشارع، رقم العقار).",
        validationRule: "نص يوضح موقع المحل ورقم العقار.",
        example: "حماة - القصور - شارع أبي الفداء - عقار 1120",
      },
      {
        name: "رقم الترخيص المهني والتسجيل النقابي",
        key: "syndicate_license_number",
        type: "string",
        required: true,
        description: "رقم تسجيل الصيدلي في سجلات نقابة الصيادلة.",
        validationRule: "نص أو رقم معتمد من النقابة.",
        example: "SYND-HMA-4512",
      },
      {
        name: "مساحة وارتفاع المحل التجاري",
        key: "shop_dimensions",
        type: "string",
        required: true,
        description: "المساحة الصافية للمحل بالمتر المربع والارتفاع الشاقولي.",
        validationRule: "مساحة صافية لا تقل عن 25 م2 وارتفاع لا يقل عن 2.60م.",
        example: "المساحة الصافية 32 م2، الارتفاع 2.85م، الواجهة 4.20م.",
      },
    ],
    validationConstraints: [
      {
        rule: "تحقيق مسافة الأمان البينية بين الصيدليات المجاورة",
        rationale: "التحقق من أن المسافة المقاسة سيراً على الأقدام بين مدخل الصيدلية المقترحة وأقرب صيدلية قائمة تحقق الحد الأدنى القانوني (عادة 75 إلى 100م).",
        severity: "error",
      },
      {
        rule: "الصفة التجارية النظامية للمحل في رخصة البناء",
        rationale: "يجب أن يكون المحل مرخصاً كـ (محل تجاري) في رخصة البناء الأصلية ولا يجوز ترخيص صيدلية في قبو سكني أو مستودع غير مرخص تجارياً.",
        severity: "error",
      },
      {
        rule: "استيفاء المتطلبات الصحية وشروط التهوية ومستودع الأدوية",
        rationale: "توفر مغسلة نظامية وتهوية كافية وعزل مناسب للأدوية عن مصادر الرطوبة والحرارة.",
        severity: "warning",
      },
    ],
    attachmentsSpecification: [
      {
        name: "سند ملكية أو عقد إيجار موثق رسمياً للمحل",
        format: "PDF / JPEG",
        maxSize: "5MB",
        isRequired: true,
        purpose: "إثبات حق الإشغال القانوني للمحل التجاري.",
        issuingAuthority: "مجلس مدينة حماة (عقد الإيجار المصدق) / المصالح العقارية",
      },
      {
        name: "شهادة التسجيل النقابي والترخيص المهني للصيدلي",
        format: "PDF",
        maxSize: "5MB",
        isRequired: true,
        purpose: "إثبات الأهلية المهنية لممارسة المهنة وإدارة الصيدلية.",
        issuingAuthority: "نقابة صيادلة سورية / وزارة الصحة",
      },
      {
        name: "مخطط كروكي ومعماري للمحل مبين عليه القياسات والمسافات",
        format: "PDF / DWG",
        maxSize: "10MB",
        isRequired: true,
        purpose: "قياس المسافات بدقة مع الصيدليات المحيطة وتدقيق المساحة الصافية.",
        issuingAuthority: "مهندس معتمد مع محضر كشف نقابي",
      },
    ],
    edgeCasesAndReturns: [
      {
        condition: "قصر المسافة المقاسة عن الحد النظامي بين الصيدلية المقترحة وصيدلية قائمة",
        action: "رفض الموقع مع تقديم مخطط المساحة الذي يوضح المسافة المقاسة بدقة وإتاحة حق التظلم.",
        returnCode: "ERR_PHARMACY_DISTANCE_VIOLATION",
      },
      {
        condition: "المحل يقع في شارع غير معتمد تجارياً أو مرخص كمرآب سيارات",
        action: "إيقاف المعاملة واشتراط إجراء تسوية وترخيص تجاري مسبق إن كان ذلك مسموحاً بموجب الضابطة.",
        returnCode: "ERR_SHOP_COMMERCIAL_STATUS",
      },
    ],
    apiPayloadExample: JSON.stringify(
      {
        service_id: "pharmacy-license",
        pharmacist: {
          name: "د. ريم بسام القنواتي",
          license_no: "SYND-HMA-4512",
          phone: "0955998877",
        },
        location: {
          property_no: 1120,
          zone: "القصور",
          area_sqm: 32.0,
          nearest_pharmacy_distance_m: 115.0,
        },
      },
      null,
      2
    ),
    faqs: [
      {
        id: "faq-pharm-01",
        category: "إداري وتشغيلي",
        question: "كيف يتم إجراء الكشف المشترك لقياس المسافة بين الصيدليات؟",
        answer: "يخرج مهندس الكشف من دائرة التنظيم برفقة مندوب نقابة الصيادلة، ويتم قياس المسافة الحقيقية بأقصر مسار مشاة نظامي بين منتصف باب الصيدلية المراد ترخيصها وباب أقرب صيدلية مرخصة.",
      },
      {
        id: "faq-pharm-02",
        category: "تقني ونموذج البيانات",
        question: "كيف يدعم النظام التحقق المكاني من مواقع الصيدليات المسجلة؟",
        answer: "يحتوي النظام على طبقة مكانية مخصصة (Pharmacies GIS Layer) تسجل مواقع كافة الصيدليات القائمة والمرخصة، وتجري خوارزمية قياس نصف القطر (Buffer Distance) للتأكد المبدئي من خلو نطاق الأمان قبل الكشف الميداني.",
      },
      {
        id: "faq-pharm-03",
        category: "مالي وقانوني",
        question: "ما هي الرسوم الواجبة لمنح الموافقة المكانية على ترخيص الصيدلية؟",
        answer: "يسدد الصيدلي رسوم الكشف الفني الميداني ورسم المعاينة المكانية ورسوم الطوابع المعتمدة في اللائحة المالية للبلدية.",
      },
      {
        id: "faq-pharm-04",
        category: "إجراءات واعتمادات",
        question: "ما هي الخطوة التالية بعد صدور موافقة دائرة التنظيم العمراني؟",
        answer: "يرسل كتاب الموافقة والمخطط المصدق رسمياً إلى مديرية الصحة وفرع نقابة الصيادلة لاستكمال الكشف الصحي ومنح رخصة الفتح ومزاولة المهنة النهائية.",
      },
    ],
  },
};

