"use client";

import { useMemo, useState } from "react";
import { ClipboardList, FileCheck2, FileText, LayoutGrid, MapPinned, MessageSquareText, Paperclip, ReceiptText, Table2, UserRound } from "lucide-react";
import type { CitizenServiceDefinition } from "@/domain/types";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";

type ServiceFilter = "all" | "service" | "inquiry";

interface CitizenServicesPageProps {
  services: CitizenServiceDefinition[];
  activeFilter: ServiceFilter;
  onFilterChange: (filter: ServiceFilter) => void;
}

const kindLabel = (kind: CitizenServiceDefinition["kind"]) => kind === "inquiry" ? "استعلام" : "طلب خدمة";

export function CitizenServicesPage({ services, activeFilter, onFilterChange }: CitizenServicesPageProps) {
  const [query, setQuery] = useState("");
  const [selectedId, setSelectedId] = useState(services[0]?.id ?? null);
  const [viewMode, setViewMode] = useState<"table" | "cards">("table");
  const filteredServices = useMemo(() => services.filter((service) => (activeFilter === "all" || service.kind === activeFilter) && `${service.name} ${service.description} ${service.unit}`.toLowerCase().includes(query.trim().toLowerCase())), [activeFilter, query, services]);
  const selected = filteredServices.find((service) => service.id === selectedId) ?? filteredServices[0];

  return <div className="flex h-full min-h-0 flex-col bg-slate-50 text-slate-800" dir="rtl">
    <header className="flex shrink-0 items-center justify-between border-b border-slate-200 bg-white px-6 py-4"><div><div className="flex items-center gap-2 text-lg font-semibold text-slate-900"><ClipboardList size={20} className="text-pink-600" />طلبات المواطنين</div><p className="mt-1 text-xs text-slate-500">كتالوج الخدمات والاستعلامات لدائرة التنظيم العمراني.</p></div><div className="flex items-center gap-2"><Badge variant="secondary">{services.length} طلبات</Badge><Badge variant="success">مفعّل</Badge></div></header>
    <div className="flex min-h-0 flex-1 flex-col gap-4 overflow-auto p-5 lg:flex-row">
      <section className="min-w-0 flex-1"><div className="mb-4 flex flex-wrap items-center gap-3"><div className="relative min-w-[220px] flex-1"><ClipboardList size={15} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ابحث باسم الطلب أو الوصف…" className="pr-9" /></div><span className="shrink-0 text-xs text-slate-500">{filteredServices.length} نتيجة</span><div className="flex items-center gap-1 rounded-lg border border-slate-200 bg-white p-1"><button type="button" onClick={() => setViewMode("table")} className={`flex items-center gap-1.5 rounded-md px-2.5 py-1.5 text-xs ${viewMode === "table" ? "bg-slate-900 text-white" : "text-slate-500 hover:bg-slate-100"}`}><Table2 size={14} />جدول</button><button type="button" onClick={() => setViewMode("cards")} className={`flex items-center gap-1.5 rounded-md px-2.5 py-1.5 text-xs ${viewMode === "cards" ? "bg-slate-900 text-white" : "text-slate-500 hover:bg-slate-100"}`}><LayoutGrid size={14} />بطاقات</button></div></div>{viewMode === "table" ? <ServicesTable services={filteredServices} selectedId={selected?.id ?? null} onSelect={setSelectedId} /> : <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{filteredServices.map((service) => <button key={service.id} type="button" onClick={() => setSelectedId(service.id)} className={`rounded-xl border bg-white p-4 text-right shadow-sm transition hover:-translate-y-0.5 hover:border-pink-300 hover:shadow-md ${selected?.id === service.id ? "border-pink-500 ring-1 ring-pink-100" : "border-slate-200"}`}><div className="mb-3 flex items-start justify-between gap-3"><span className={`grid size-9 shrink-0 place-items-center rounded-lg ${service.kind === "inquiry" ? "bg-cyan-50 text-cyan-700" : "bg-pink-50 text-pink-600"}`}>{service.kind === "inquiry" ? <MessageSquareText size={17} /> : <MapPinned size={17} />}</span><Badge variant={service.kind === "inquiry" ? "outline" : "default"}>{kindLabel(service.kind)}</Badge></div><div className="text-sm font-semibold text-slate-900">{service.name}</div><p className="mt-2 line-clamp-2 text-xs leading-5 text-slate-500">{service.description}</p><div className="mt-3 flex items-center justify-between text-[10px] text-slate-400"><span>{service.unit}</span><span>{service.attachments.length ? `${service.attachments.length} مرفقات` : "بلا مرفقات"}</span></div></button>)}</div>}{filteredServices.length === 0 && <div className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">لا توجد طلبات مطابقة.</div>}</section>
      <aside className="h-fit w-full shrink-0 rounded-xl border border-slate-200 bg-white p-5 shadow-sm lg:w-[390px]">{selected ? <ServiceDetails service={selected} /> : <div className="py-8 text-center text-sm text-slate-500">اختر طلبًا لعرض تفاصيله.</div>}</aside>
    </div>
  </div>;
}

function ServicesTable({ services, selectedId, onSelect }: { services: CitizenServiceDefinition[]; selectedId: string | null; onSelect: (id: string) => void }) {
  return <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 bg-slate-50 px-4 py-2.5"><div className="flex items-center gap-2 text-xs font-semibold text-slate-700"><Table2 size={14} className="text-pink-600" />سجل طلبات المواطنين</div><span className="text-[10px] text-slate-400">اضغط على الصف لعرض التفاصيل</span></div><div className="overflow-x-auto"><table className="min-w-[1040px] w-full border-collapse text-right text-xs" dir="rtl"><thead><tr className="border-b border-slate-200 bg-slate-100 text-[10px] font-semibold text-slate-500"><th className="w-10 px-3 py-3">#</th><th className="min-w-[250px] px-3 py-3">اسم الطلب</th><th className="min-w-[105px] px-3 py-3">النوع</th><th className="min-w-[160px] px-3 py-3">المجال</th><th className="min-w-[130px] px-3 py-3">الوحدة</th><th className="min-w-[85px] px-3 py-3">القناة</th><th className="min-w-[105px] px-3 py-3">الرسم</th><th className="min-w-[85px] px-3 py-3">الأولوية</th></tr></thead><tbody>{services.map((service, index) => <tr key={service.id} onClick={() => onSelect(service.id)} className={`cursor-pointer border-b border-slate-100 transition last:border-0 hover:bg-pink-50/60 ${selectedId === service.id ? "bg-pink-50" : index % 2 ? "bg-white" : "bg-slate-50/40"}`}><td className="px-3 py-3 font-mono text-[10px] text-slate-400">{index + 1}</td><td className="px-3 py-3"><div className="font-semibold text-slate-800">{service.name}</div><div className="mt-1 max-w-[300px] truncate text-[10px] text-slate-400">{service.description}</div></td><td className="px-3 py-3"><Badge variant={service.kind === "inquiry" ? "outline" : "default"}>{kindLabel(service.kind)}</Badge></td><td className="px-3 py-3 text-slate-600">{service.domain}</td><td className="px-3 py-3 text-slate-600">{service.unit}</td><td className="px-3 py-3 text-slate-600">{service.channel}</td><td className="px-3 py-3 font-medium text-slate-700">{service.fee ? `${service.fee.amount.toLocaleString("ar-SY")} ل.س` : "—"}</td><td className="px-3 py-3"><Badge variant={service.priority === "رئيسي" ? "success" : "secondary"}>{service.priority}</Badge></td></tr>)}</tbody></table></div></div>;
}

function ServiceDetails({ service }: { service: CitizenServiceDefinition }) {
  return <div className="space-y-5"><div className="flex items-start justify-between gap-3"><div><Badge variant={service.kind === "inquiry" ? "outline" : "default"}>{kindLabel(service.kind)}</Badge><h2 className="mt-2 text-base font-semibold leading-7 text-slate-950">{service.name}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{service.description}</p></div><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-pink-50 text-pink-600">{service.kind === "inquiry" ? <MessageSquareText size={19} /> : <MapPinned size={19} />}</span></div>
    <div className="grid grid-cols-2 gap-2 text-xs"><Info label="الجهة" value={service.directorate} /><Info label="الوحدة" value={service.department} /><Info label="القناة" value={service.channel} /><Info label="الأولوية" value={service.priority} /></div>
    {service.fee && <div className="flex items-center justify-between rounded-lg border border-pink-100 bg-pink-50 px-3 py-2.5 text-xs"><span className="flex items-center gap-2 text-pink-700"><ReceiptText size={14} />{service.fee.label}</span><strong className="text-pink-800">{service.fee.amount.toLocaleString("ar-SY")} {service.fee.currency}</strong></div>}
    <DetailList icon={<UserRound size={14} />} title="البيانات المطلوبة" items={service.requiredFields} empty="لا توجد بيانات إضافية محددة." />
    <DetailList icon={<Paperclip size={14} />} title="المرفقات" items={service.attachments} empty="لا يتطلب مرفقات إضافية." />
    <div><div className="mb-2 flex items-center gap-2 text-xs font-semibold text-slate-700"><FileText size={14} className="text-cyan-700" />المخرج</div><div className="rounded-lg bg-slate-50 p-3 text-xs leading-6 text-slate-600">{service.response}</div></div>
    <div><div className="mb-2 flex items-center gap-2 text-xs font-semibold text-slate-700"><FileCheck2 size={14} className="text-emerald-700" />مراحل الطلب</div><ol className="space-y-2">{service.stages.map((stage) => <li key={stage.order} className="flex gap-2 text-xs"><span className="grid size-5 shrink-0 place-items-center rounded-full bg-cyan-50 font-semibold text-cyan-700">{stage.order}</span><span className="leading-5 text-slate-600"><strong className="text-slate-800">{stage.name}</strong><br />{stage.owner}</span></li>)}</ol></div>
    {service.returnReasons?.length ? <DetailList icon={<FileText size={14} />} title="أسباب الإرجاع" items={service.returnReasons} empty="" tone="warning" /> : null}
    {service.authorityNotes?.length ? <DetailList icon={<FileCheck2 size={14} />} title="صلاحيات وملاحظات الاعتماد" items={service.authorityNotes} empty="" tone="info" /> : null}
  </div>;
}

function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-slate-50 p-2.5"><div className="text-[10px] text-slate-400">{label}</div><div className="mt-1 font-medium leading-5 text-slate-700">{value}</div></div>; }

function DetailList({ icon, title, items, empty, tone = "default" }: { icon: React.ReactNode; title: string; items: string[]; empty: string; tone?: "default" | "warning" | "info" }) { return <div><div className="mb-2 flex items-center gap-2 text-xs font-semibold text-slate-700">{icon}{title}</div>{items.length ? <ul className={`space-y-1.5 rounded-lg p-3 text-xs leading-5 ${tone === "warning" ? "bg-amber-50 text-amber-800" : tone === "info" ? "bg-cyan-50 text-cyan-800" : "bg-slate-50 text-slate-600"}`}>{items.map((item) => <li key={item} className="flex gap-2"><span className="mt-2 size-1 shrink-0 rounded-full bg-current" />{item}</li>)}</ul> : <div className="rounded-lg bg-slate-50 p-3 text-xs text-slate-400">{empty}</div>}</div>; }

export function CitizenServicesSidebar({ services, activeFilter, onFilterChange }: Pick<CitizenServicesPageProps, "services" | "activeFilter" | "onFilterChange">) {
  const items: Array<{ id: ServiceFilter; label: string; count: number }> = [{ id: "all", label: "كل الطلبات", count: services.length }, { id: "service", label: "طلبات الخدمات", count: services.filter((service) => service.kind === "service").length }, { id: "inquiry", label: "الاستعلامات", count: services.filter((service) => service.kind === "inquiry").length }];
  return <div className="min-h-0 flex-1 overflow-auto px-2 py-3"><div className="mb-2 px-2 text-[10px] font-semibold text-slate-500">أنواع طلبات المواطنين</div>{items.map((item) => <button key={item.id} type="button" onClick={() => onFilterChange(item.id)} className={`mb-1 flex w-full items-center justify-between rounded-md px-3 py-2 text-right text-xs ${activeFilter === item.id ? "bg-pink-50 text-pink-700" : "text-slate-600 hover:bg-slate-100"}`}><span>{item.label}</span><span>{item.count}</span></button>)}</div>;
}
